# OTA A/B-test Visibility Boost

## Test Design

## Structure

1. Input Data (delta, alpha, power)
2. Query Data:   
    2.1. Get cities_list from Framework results: SQL   
    2.2. Get Baseline Conversion Rate (p): SQL    
    2.3. Get average daily users (daily_users): SQL   
3. Get Sample Size and Estimated Experiment Duration (n, t): sample_size.py

In [1]:
import sys
from pathlib import Path

# Adding project root to Python path
PROJECT_ROOT = Path.cwd()

# If running from /notebooks → go up one level
if (PROJECT_ROOT / "src").exists() is False:
    PROJECT_ROOT = PROJECT_ROOT.parent

import sys
sys.path.append(str(PROJECT_ROOT))

# 1. Input Data

In [2]:
# 1. Input Data
delta = 0.005
alpha = 0.05
power = 0.8

# Framework results
FRAMEWORK_RESULTS_TABLE = "analytics.market_equilibrium_and_drift_v1_analytical"
signal = "decline_profile"
signal_value = "DEMAND_CRISIS"

## 2. Query Data

### Connection to db

In [3]:
# Connecting to database
import pandas as pd
from sqlalchemy import text

from dotenv import load_dotenv
load_dotenv()

from src.db import get_engine

engine = get_engine()
engine

Engine(postgresql+psycopg2://nomad:***@localhost:5433/nomad_db)

In [4]:
# db connection test

TEST_SQL = """
SELECT
        city_name,
        city_id,
        country_code
  FROM  nomad.cities
 WHERE  UPPER(country_code) = 'TH'
"""

test_df = pd.read_sql_query(text(TEST_SQL), engine)
test_df.head(3)

    city_name  city_id country_code
0     Bangkok      133           TH
1      Phuket      134           TH
2  Chiang Mai      135           TH

## 2. Query Data from MED Framework

> **NOTE!** The next cell returns an ERROR, since `nomad_db` doesn't have sessions data. It's just an example.

In [ ]:
# Query data from Framework
# 2.1. Getting cities list from Framework results
# 2.2. Getting a baseline cr 
# 2.3. Getting avg daily users

FINAL_SQL = text(f"""
WITH    cities_list AS (
        SELECT DISTINCT
                city_name,
                country_code,
                stay_week,
                {signal}
          FROM  {FRAMEWORK_RESULTS_TABLE}
         WHERE  {signal} = :signal_value
                AND stay_week = (
                    SELECT MAX(stay_week)
                    FROM {FRAMEWORK_RESULTS_TABLE}
                )
        ),

        filtered_sessions AS (
        SELECT
                t.city_name,
                t.country_code,
                t.session_date,
                t.session_id,
                t.booking_id,
                list.{signal}
          FROM  nomad.table t
          JOIN  cities_list list
                ON list.city_name = t.city_name
                AND list.country_code = t.country_code
         WHERE  t.session_date BETWEEN list.stay_week - INTERVAL '52 weeks'
                                AND list.stay_week
        ),

        daily_users AS (
        SELECT
                city_name,
                country_code,
                {signal},
                session_date,
                COUNT(DISTINCT session_id) AS daily_users
          FROM  filtered_sessions
         GROUP  BY 1,2,3,4
        )

SELECT
        fs.city_name,
        fs.country_code,
        fs.{signal},
        
        -- baseline conversion rate
        AVG(CASE WHEN fs.booking_id IS NOT NULL THEN 1 ELSE 0 END) AS baseline_cr,
        
        -- avg daily users
        AVG(du.daily_users) AS avg_daily_users

  FROM  filtered_sessions fs
  JOIN  daily_users du
        ON fs.city_name = du.city_name
        AND fs.country_code = du.country_code
        AND fs.session_date = du.session_date

 GROUP  BY
        fs.city_name,
        fs.country_code,
        fs.{signal}
""")

cities_baseline_df = pd.read_sql_query(
    FINAL_SQL, 
    engine,
    params={"signal_value": signal_value}
)
cities_baseline_df

### 2.1. DEMO: Getting Cities List from MED Framework Results

Demonstration that connection and pipeline are both work.

In [5]:
CITIES_LIST = text(f"""
SELECT DISTINCT
        city_name,
        country_code,
        stay_week,
        {signal}
    FROM  {FRAMEWORK_RESULTS_TABLE}
    WHERE  {signal} = :signal_value
        AND stay_week = (
            SELECT MAX(stay_week)
            FROM {FRAMEWORK_RESULTS_TABLE}
        )
""")

cities_list_df = pd.read_sql_query(
    CITIES_LIST, 
    engine,
    params={"signal_value": signal_value}
)
cities_list_df

  city_name country_code  stay_week decline_profile
0     Krabi           TH 2026-02-23   DEMAND_CRISIS
1    Phuket           TH 2026-02-23   DEMAND_CRISIS

# 3. Get Sample Size and Estimated Experiment Duration

### 3.1. Assumptions

Input assumptions:
- Baseline CR: baseline_cr = 0.05
- Daily Users: avg_daily_users = 10000

In [6]:
# Complete Input Table

cities_baseline_df = (
    cities_list_df
    .assign(
        baseline_cr=0.05,
        avg_daily_users=5000
    )
)

cities_baseline_df

,city_name,country_code,stay_week,decline_profile,baseline_cr,avg_daily_users
0,Krabi,TH,2026-02-23,DEMAND_CRISIS,0.05,5000
1,Phuket,TH,2026-02-23,DEMAND_CRISIS,0.05,5000

## 3.2. Sample Size and Estimated Experiment Duration

In [7]:
from src.stats.sample_size import sample_size_proportion, estimate_experiment_duration

# Getting the rest of input data
p = cities_baseline_df['baseline_cr'].mean()
daily_users = cities_baseline_df['avg_daily_users'].sum()

# Sample Size
n = sample_size_proportion(p, delta)

# Estimated Experiment Duration
days = estimate_experiment_duration(n, daily_users / 2)

print("Sample size per group:", n)
print("Estimated duration (days):", days)

Sample size per group: 29826
Estimated duration (days): 6

**Estimated Experiment Duration(days)** = 6 days.   
But, due to weekday vs weekend effect, noise and user behavior variability, it's better to have at least a week+ duration: **10-14 days**.

In [10]:
days = 14

## 3.3. Collecting the whole Input Data

In [12]:
import json

params = {
    "baseline_cr": p,
    "delta": delta,
    "alpha": alpha,
    "power": power,
    "treatment_cr": p + delta,
    "sample_size_per_group": n,
    "total_sample_size": n * 2,
    "estimated_days": days
}

with open("../outputs/input_data.json", "w") as f:
    json.dump(params, f, indent=2)


with open("../outputs/input_data.json", "r") as f:
    params = json.load(f)

params

{'baseline_cr': 0.05,
 'delta': 0.005,
 'alpha': 0.05,
 'power': 0.8,
 'treatment_cr': 0.055,
 'sample_size_per_group': 29826,
 'total_sample_size': 59652,
 'estimated_days': 14}