# A/B-test Visibility Boost Analysis

### Metadata

In [46]:
import pandas as pd
import numpy as np
from scipy.stats import norm

# Required Metadata

# Experiment metadata
EXP_NAME = "thailand_ab_test_visibility_boost"
EXP_RESULTS_TABLE = "analytics.ab_test_simulation_v1"

### Connection to database

In [ ]:
# Connecting to database
from sqlalchemy import text

from dotenv import load_dotenv
load_dotenv()

from src.db import get_engine

engine = get_engine()
engine

Engine(postgresql+psycopg2://nomad:***@localhost:5433/nomad_db)

In [7]:
# Database connection test

TEST_SQL = f"""
SELECT
        group_name,
        COUNT(*) AS sample_size
  FROM  {EXP_RESULTS_TABLE}
 GROUP  BY 1
 ORDER  BY 1
"""

test_df = pd.read_sql_query(text(TEST_SQL), engine)
test_df

  group_name  sample_size
0    control        29826
1  treatment        29826

## Querying Data from the Experiment

### Hypotheses

```code
H0 (null):          p_treatment  = p_control    (no effect)
H1 (alternative):   p_treatment != p_control    (effect exists)
```

In [13]:
# Fetching metrics for A/B-test analysis
# p_control, p_treatment: control, treatment group Conversion Rate
# n_control, n_treatment: control, treatment group Sample Size

FINAL_SQL = f"""
SELECT
        group_name,
        AVG(conversion) AS p,
        COUNT(*)        AS n
  FROM  {EXP_RESULTS_TABLE}
 GROUP  BY group_name
 ORDER  BY group_name
"""

exp_df = pd.read_sql_query(
    text(FINAL_SQL),
    engine,
    index_col='group_name'
)

exp_df

                   p      n
group_name
control     0.049822  29826
treatment   0.054248  29826

# A/B-test Analysis

### Observed Metrics

In [23]:
# Observed Metrics

# Conversion Rate
p_control = exp_df.loc['control', 'p']
p_treatment = exp_df.loc['treatment', 'p']

# Sample Size
n_control = exp_df.loc['control', 'n']
n_treatment = exp_df.loc['treatment', 'n']

### Analysis

In [ ]:
# Difference in Conversion Rate (observed delta)

delta_observed = p_treatment - p_control
delta_observed

np.float64(0.0044256688795011045)

Is 0.0044 big enough compared to noise?

In [54]:
# Standard Error (SE)
# SE = sqrt(  p_pool * (1 - p_pool) * (1/n_control + 1/n_treatment) )
# Where p_pool (pooled conversion rate) = (p_control * n_control + p_treatment * n_treatment) / (n_control + n_treatment)

p_pool = (
    p_control * n_control + p_treatment * n_treatment
) / (n_control + n_treatment)

se = np.sqrt(
    p_pool * (1 - p_pool)
    * (1/n_control + 1/n_treatment)
)

# Z-score (how many SE away we're from 0)
# z = (observed difference) / SE

z = delta_observed / se

# Getting a p-value
p_value = 2 * (1 - norm.cdf(abs(z)))

print(f"se: {se}\nz-score: {z}\np-value: {p_value}")

se: 0.0018187037523679974
z-score: 2.433419337117864
p-value: 0.014956967596891246

## Statistical Significance Decision

At this point we have to make a decision about **statistical** significance of observed delta between conversion rates. To make, we load our $\alpha$ from test design input metrics and compare it to p-value:

p < $\alpha$        effect likely due to experiment (visibility boost)    
p $\geq$ $\alpha$   effect is probably noise

In [51]:
import json

# Load Input Data from Test Design
with open("../outputs/input_data.json", "r") as f:
    params = json.load(f)

# Simulation Input Parameters
alpha = params["alpha"]

# Statistical Significance
print(f"alpha: {alpha}\np-value: {p_value:.3f}\n")
if p_value < alpha:
    print("Reject H0: STATISTICALLY SIGNIFICANT EFFECT")
else:
    print("Fail to reject H0: NOISE")

alpha: 0.05
p-value: 0.015

Reject H0: STATISTICALLY SIGNIFICANT EFFECT

## Confidence Interval (CI)

CI answers how big is the effect?

In [49]:
# Confidence Interval (CI)
# CI = delta +/- Za/2 * SE

# Getting Za
z_alpha = norm.ppf(1 - alpha/2) 

# CI
ci_lower_band = delta_observed - z_alpha * se
ci_upper_band = delta_observed + z_alpha * se

print(f"We're {1 - alpha}% confident that the true uplift lies between {ci_lower_band:.2%} and {ci_upper_band:.2%}")

We're 0.95% confident that the true uplift lies between 0.09% and 0.80%